#
# This file is part of LiteX-Boards.
#
# Copyright (c) 2026 LiteX-Hub community
# SPDX-License-Identifier: BSD-2-Clause

# AWS EC2 F2 FPGA (AMD/Xilinx Virtex UltraScale+ VU47P).
#
# F2 Custom Logic sits behind the AWS Shell. Physical PCIe/DDR pins are owned by
# the Shell; IOs below are CL ports (no package pin locations).

from litex.build.generic_platform import Pins, Subsignal
from litex.build.generic_programmer import GenericProgrammer
from litex.build.xilinx import XilinxUSPPlatform
from litex.soc.interconnect.axi import AXILiteInterface

# IOs ----------------------------------------------------------------------------------------------

_io = [
    # Shell clocks / reset (clk_main_a0 default recipe A0 = 250 MHz).
    ("clk_main_a0", 0, Pins(1)),
    ("clk_hbm_ref", 0, Pins(1)), # 100 MHz HBM reference clock from the Shell.
    ("rst_main_n",  0, Pins(1)),

    # Virtual LEDs / DIP switches exposed by the F2 Shell (fpga-get-virtual-led).
    ("user_led",  0, Pins(1)),
    ("user_led",  1, Pins(1)),
    ("user_led",  2, Pins(1)),
    ("user_led",  3, Pins(1)),
    ("user_led",  4, Pins(1)),
    ("user_led",  5, Pins(1)),
    ("user_led",  6, Pins(1)),
    ("user_led",  7, Pins(1)),
    ("user_sw",   0, Pins(1)),
    ("user_sw",   1, Pins(1)),
    ("user_sw",   2, Pins(1)),
    ("user_sw",   3, Pins(1)),
    ("user_sw",   4, Pins(1)),
    ("user_sw",   5, Pins(1)),
    ("user_sw",   6, Pins(1)),
    ("user_sw",   7, Pins(1)),
]

# AXI-Lite OCL (AppPF BAR0) ------------------------------------------------------------------------

def get_ocl_ios(name="ocl"):
    return AXILiteInterface(data_width=32, address_width=32).get_ios(name)

# Programmer ---------------------------------------------------------------------------------------

class AWSF2Programmer(GenericProgrammer):
    """Load an Amazon FPGA Image (AGFI) onto an F2 instance slot."""

    def __init__(self, slot=0):
        GenericProgrammer.__init__(self)
        self.slot = slot

    def load_bitstream(self, bitstream_file):
        # bitstream_file is an AGFI id (agfi-...), not a Vivado .bit file.
        self.call(["fpga-load-local-image", "-S", str(self.slot), "-I", bitstream_file])

# CL wrapper ---------------------------------------------------------------------------------------

def write_cl_wrapper(filename, soc_name="aws_f2"):
    """Write an HDK Custom Logic wrapper that instantiates the LiteX SoC."""
    leds = ",\n".join(
        f"        .user_led{i}(user_led[{i}])" for i in range(8)
    )
    contents = f"""// Generated by LiteX-Boards for AWS EC2 F2.
// Copy this file plus the LiteX SoC Verilog into an AWS HDK CL example and build an AFI.

module cl_litex (
`include "cl_ports.vh"
);

  logic rst_main_n_sync;
  logic pre_sync_rst_n;
  always @(posedge clk_main_a0) begin
    if (!rst_main_n) begin
      pre_sync_rst_n  <= 1'b0;
      rst_main_n_sync <= 1'b0;
    end else begin
      pre_sync_rst_n  <= 1'b1;
      rst_main_n_sync <= pre_sync_rst_n;
    end
  end

`include "unused_flr_template.inc"
`include "unused_ddr_template.inc"
`include "unused_cl_sda_template.inc"
`include "unused_apppf_irq_template.inc"
`include "unused_dma_pcis_template.inc"
`include "unused_pcim_template.inc"

  // Amazon Vendor ID 0x1D0F with Device ID in 0xF000-0xF0FF.
  assign cl_sh_id0 = 32'hF010_1D0F;
  assign cl_sh_id1 = 32'h1D51_FEDC;

  assign cl_sh_status0     = 32'h0;
  assign cl_sh_status1     = 32'h0;
  assign cl_sh_status2     = 32'h0;
  assign cl_sh_dma_wr_full = 1'b0;
  assign cl_sh_dma_rd_full = 1'b0;

  wire [7:0] user_led;
  assign cl_sh_status_vled = {{8'd0, user_led}};

  {soc_name} {soc_name}_i (
        .clk_main_a0(clk_main_a0),
        .rst_main_n(rst_main_n_sync),
{leds},
        .ocl_awvalid(ocl_cl_awvalid),
        .ocl_awready(cl_ocl_awready),
        .ocl_awaddr(ocl_cl_awaddr),
        .ocl_awprot(3'd0),
        .ocl_wvalid(ocl_cl_wvalid),
        .ocl_wready(cl_ocl_wready),
        .ocl_wdata(ocl_cl_wdata),
        .ocl_wstrb(ocl_cl_wstrb),
        .ocl_bvalid(cl_ocl_bvalid),
        .ocl_bready(ocl_cl_bready),
        .ocl_bresp(cl_ocl_bresp),
        .ocl_arvalid(ocl_cl_arvalid),
        .ocl_arready(cl_ocl_arready),
        .ocl_araddr(ocl_cl_araddr),
        .ocl_arprot(3'd0),
        .ocl_rvalid(cl_ocl_rvalid),
        .ocl_rready(ocl_cl_rready),
        .ocl_rdata(cl_ocl_rdata),
        .ocl_rresp(cl_ocl_rresp)
  );

endmodule
"""
    with open(filename, "w", encoding="utf-8") as f:
        f.write(contents)

# Platform -----------------------------------------------------------------------------------------

class Platform(XilinxUSPPlatform):
    default_clk_name   = "clk_main_a0"
    default_clk_period = 1e9/250e6

    def __init__(self, toolchain="vivado"):
        XilinxUSPPlatform.__init__(self, "xcvu47p-fsvh2892-2-e", _io, toolchain=toolchain)

    def create_programmer(self, slot=0):
        return AWSF2Programmer(slot=slot)

    def do_finalize(self, fragment):
        XilinxUSPPlatform.do_finalize(self, fragment)
        self.add_period_constraint(self.lookup_request("clk_main_a0", loose=True), 1e9/250e6)
        self.add_period_constraint(self.lookup_request("clk_hbm_ref", loose=True), 1e9/100e6)
